name: Jekyll site CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # Specify the Ruby version you are using
    - name: Install bundler 2.4.22
      run: gem install bundler -v 2.4.22
    - name: Install dependencies
      run: bundle _2.4.22_ install
    - name: Build the site
      run: bundle _2.4.22_ exec jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
